use crate::fixed::FixedPoint;

pub const STAGE_WIDTH: i32 = 1200;
pub const STAGE_HEIGHT: i32 = 600;
pub const GROUND_Y: i32 = 500;

/// Walk speed: 3.5 px/frame — slow enough to whiff-punish, fast enough to close distance
pub const PLAYER_SPEED: FixedPoint = FixedPoint(3500);
/// Jump velocity: -11 px/frame upward — lower arc for tighter anti-air windows
pub const JUMP_VELOCITY: FixedPoint = FixedPoint(-11000);
/// Gravity: 0.55 px/frame² — faster fall so jumps don't float
pub const GRAVITY: FixedPoint = FixedPoint(550);

/// 1200 HP — targets 15-20 second rounds with moderate aggression
pub const MAX_HEALTH: i32 = 1200;
/// 100 energy — two specials from full, regenerated by landing hits
pub const MAX_ENERGY: i32 = 100;
/// 60 second rounds — keeps matches decisive, prevents excessive turtling
pub const ROUND_TIME_SECONDS: i32 = 60;
pub const TICKS_PER_SECOND: i32 = 60;
/// Rollback snapshot history depth (8 frames ≈ 133ms)
pub const BUFFER_SIZE: usize = 8;
/// Input history for rollback resimulation (2 seconds)
pub const INPUT_BUFFER_SIZE: usize = 120;

/// Projectile speed: 6 px/frame — reactable at mid-range, punishes full-screen zoning
pub const PROJECTILE_SPEED: i32 = 6;
/// Projectile damage: 40 — less than heavy attack to reward melee risk
pub const PROJECTILE_DAMAGE: i32 = 40;
/// Projectile hitstun: 14 frames — enough for advantage but not a free combo
pub const PROJECTILE_HITSTUN: i32 = 14;
/// Projectile lifetime: 75 frames — disappears before crossing full stage twice
pub const PROJECTILE_LIFETIME: i32 = 75;
/// Energy cost for special moves: 30 — limits spam to ~3 specials from full meter
pub const SPECIAL_ENERGY_COST: i32 = 30;
/// Energy gained per hit landed: 8 — rewards aggression, ~12 hits to refill
pub const ENERGY_PER_HIT: i32 = 8;
/// Knockdown recovery: 36 frames — punishing but not oppressive on wakeup
pub const KNOCKDOWN_FRAMES: i32 = 36;
/// Knockdown threshold: 70 damage — heavy attacks and specials cause knockdown
pub const KNOCKDOWN_THRESHOLD: i32 = 70;
/// Dash strike speed multiplier (relative to walk speed)
pub const DASH_STRIKE_SPEED_MULT: i32 = 3;
/// Combo hitstun decay per hit: 7% — prevents infinite combos, practical limit ~6 hits
pub const COMBO_DECAY_PER_HIT: i32 = 70;
/// Minimum hitstun scale: 25% — even deep combos can still link with tight timing
pub const COMBO_MIN_SCALE: i32 = 250;
/// Block chip damage: 20% of attack damage — blocking is safe but not free
pub const BLOCK_CHIP_PERCENT: i32 = 20;
/// Blockstun multiplier: hitstun * 0.6 — defenders recover faster from blocked hits
pub const BLOCKSTUN_RATIO: i32 = 600;
